### ISSUE TITLE
数据库中是不是可以体现一下这些图标对 “线性”“填充”“双色”“多色” 是否支持的提示！

### ISSUE THREAD

**Issue by zdy1988** [icon-space/IconSpace#13]
我看到doc里面写道，项目会自动生成对应的react svg vue vue-next代码，要知道react和vue代码中有涉及到填充、双色和多色的情况是怎么辨别的呢？

如果可以辨别，那有没有一种方式可以快速统计出没有线性模式的图标，比如 more，还有一些品牌类的图标比如 alipay、dongchedi、facebook-one等，我这里“没有线性模式的图标”就是指不能修改线段的粗细，线性模式和填充模式展示出来的图标都一样的图标！

这样，数据库中是不是可以体现一下这些图标对 “线性”“填充”“双色”“多色” 是否支持的提示！

**Comment by lhlyu** [comment]
可以知道图标对应的风格，[代码](https://github.com/icon-space/IconSpace/blob/main/packages/compiler/src/transformer/DynamicColorTransformer.ts#L45)
你所说的数据库是指`db.csv`文件吗

**Comment by zdy1988** [comment]
嗯，是的！我看到你源码里没有icons.json这个数据库了！

**Comment by zdy1988** [comment]
由于我把图标用在wpf里，所以会关心其中有那些是线性的，那些是填充的，我把填充图标强行线性的话，就剩外轮廓了...

**Comment by lhlyu** [comment]
> 嗯，是的！我看到你源码里没有icons.json这个数据库了！

因为我尽可能的减少文件数量，所以这个`icons.json`文件是通过脚本生成的，以后可以多加个`theme`字段来说明图标支持哪种风格

**Comment by zdy1988** [comment]
我还有[一个转换问题](https://github.com/bytedance/IconPark/issues/718)，不知道你有没有什么看法和解决方案，目前我对svg的认识还很浅薄...

**Comment by lhlyu** [comment]
> 我还有[一个转换问题](https://github.com/bytedance/IconPark/issues/718)，不知道你有没有什么看法和解决方案，目前我对svg的认识还很浅薄...

这问题我不会，你可以问一下chatgpt
