### ISSUE TITLE
这个没有直接将原项目代码fork过来吗？

### ISSUE THREAD

**Issue by bzw1204** [icon-space/IconSpace#3]

**Comment by lhlyu** [comment]
原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM

**Comment by bzw1204** [comment]
> 原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM

原有功能一模一样吗？

**Comment by bzw1204** [comment]
> 原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM

大佬，有组织群吗？

**Comment by lhlyu** [comment]
> > 原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM
> 
> 原有功能一模一样吗？

除了安装的包名不一样，其他都一样

**Comment by lhlyu** [comment]
> > 原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM
> 
> 大佬，有组织群吗？

没有，不太喜欢管理群，如果你愿意创建的话，我可以置顶

**Comment by bzw1204** [comment]
> > > 原项目是手动发布包到NPM，我改成github action了，原项目有些问题，我进行了改造，现在是只要提供svg原图，github action 会自动生成 vue react svg vue-next 相应的代码再发布到NPM
> > 
> > 
> > 大佬，有组织群吗？
> 
> 没有，不太喜欢管理群，如果你愿意创建的话，我可以置顶
面对面
![image](https://user-images.githubusercontent.com/9693637/222063392-d65150a7-fe33-4b62-b876-d367129c2fcf.png)
来，大佬，欢迎加入
