### ISSUE TITLE
outStrokeColor has no effect on the icon

### ISSUE THREAD

**Issue by bzw1204** [icon-space/IconSpace#4]
原项目中有一个BUG，连接地址： https://github.com/bytedance/IconPark/issues/347
我Fork本项目想修复，但是没有看到对应源码，是没有开源出来吗

**Comment by lhlyu** [comment]
因为采用的是自动生成，所以这部分代码在[这里](https://github.com/icon-space/IconSpace/blob/main/packages/compiler/src/generator/SvgRuntimeGenerator.ts)，上面的提案我看着有点懵逼，因为我一般不会直接使用svg库，我用的最多的是vue-next和react

**Comment by lhlyu** [comment]
已解决，[c8caadc](https://github.com/icon-space/IconSpace/commit/c8caadc5dd49100eeaad9eb28b875e37a0d0969f)
